apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafeio-auth-depl

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cafeio-auth
  template:
    metadata:
      labels:
        app: cafeio-auth
    spec:
      containers:
        - name: cafeio-auth
          image: jontopanotti/cafeio-auth
          # image: us.gcr.io/cafeio-dev/cafeio-auth
          imagePullPolicy: Never
          env: 
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY 
            - name: MONGO_URI
              value: 'mongodb://mongo-srv:27017/auth'
---
apiVersion: v1
kind: Service
metadata:
  name: cafeio-auth-srv

spec:
  selector:
    app: cafeio-auth
  ports:
    - name: cafeio-auth
      protocol: TCP
      port: 3000
      targetPort: 3000
