apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafeio-products-depl

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cafeio-products
  template:
    metadata:
      labels:
        app: cafeio-products
    spec:
      containers:
        - name: cafeio-products
          image: jontopanotti/cafeio-products
          imagePullPolicy: Never
          env: 
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY 
            - name: MONGO_URI
              value: 'mongodb://mongo-srv:27017/products'
---
apiVersion: v1
kind: Service
metadata:
  name: cafeio-products-srv

spec:
  selector:
    app: cafeio-products
  ports:
    - name: cafeio-products
      protocol: TCP
      port: 3000
      targetPort: 3000
