apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafeio-orders-depl

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cafeio-orders
  template:
    metadata:
      labels:
        app: cafeio-orders
    spec:
      containers:
        - name: cafeio-orders
          image: jontopanotti/cafeio-orders
          #image: us.gcr.io/cafeio-dev/cafeio-orders
          # imagePullPolicy: Never
          env: 
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY 
            - name: MONGO_URI
              value: 'mongodb://mongo-srv:27017/orders'
---
apiVersion: v1
kind: Service
metadata:
  name: cafeio-orders-srv

spec:
  selector:
    app: cafeio-orders
  ports:
    - name: cafeio-orders
      protocol: TCP
      port: 3000
      targetPort: 3000
